### ISSUE TITLE
iOS cannot capture input well

### ISSUE THREAD

**Issue by kbumsik** [chris-rudmin/opus-recorder#120]
Hello, I am just trying thing around here.
Firstly, thank you for providing this library.
In your test site, https://rawgit.com/chris-rudmin/Recorderjs/master/example/encoder.html
both Firefox and Chrome work well but I have a problem with iOS Safari.

On iOS (v11.2.1), although it produces a .opus file the file doesn't sound anything with a little bit of white noise (the white noise may be from my headphone).

I tested it with every encoderSampleRate available: 8000, 12000, 16000, 24000, 48000. But the result is the same.

Is there any special configuration for iOS, or did I miss anything?

**Comment by rowntreerob** [comment]
pardon the intrusion , im not the author ... i have been eval  this lib .   :Your symptom may be due to no 
safari browser support for playback of the blob created by [the recorder](https://github.com/chris-rudmin/opus-recorder/blob/master/example/encoder.html#L111)  Using a native audio tag to playback that mime type wont work (no media support on safari) .  Instead of just setting the audio.src to the blob url , you could consider implementing your own playback button , and supporting that playback implementation with the proper Opus codec supplied in ./dist/decoderWorker.min.js

**Comment by kbumsik** [comment]
@rowntreerob Thank you for a comment. But I what I mean is I was able to play it but I could not hear anything. I aware of the iOS Opus playback problem. So what I did is copying the record file to another app that supports Opus codec (e.g. nPlayer, VLC...) using “Open in ...” feature...

**Comment by kbumsik** [comment]
Oh, I tried it again and it works very well. It’s super wired. I don’t know if I did something wrong with my iPhone but it works now.....
I close this issue. Anyway thank you for this great library!
