### ISSUE TITLE
stop() method doesn't stop the worker

### ISSUE THREAD

**Issue by stephnicolas** [chris-rudmin/opus-recorder#146]
On Chrome desktop on Windows, a call to stop() doesn't stop the worker encoderWorker.min.js
remarks: the stop can be called without a start, it's only called to stop the worker before the creation of another Recorder
Thanks
Stephane

**Comment by chris-rudmin** [comment]
I see. Yup we can fix that.

**Comment by IvanDreamer** [comment]
For me stop() does not fire "ondataavailable" in Chrome and Firefox. Even I was checking example and it didn't work as well.

**Comment by chris-rudmin** [comment]
@IvanDreamer You can configure the WebWorker path with config option `encoderPath`.
> encoderPath - (optional) Path to encoderWorker.min.js or waveWorker.min.js worker script. Defaults to encoderWorker.min.js

**Comment by chris-rudmin** [comment]
@stephnicolas I was just looking into fixing this, however I will leave the behaviour as is. `stop()` is not supposed to kill the worker. It actually starts another instance so that it is ready to record again.  When you are finished with the recorder instance, and you want to kill the worker you can call `rec.encoder.terminate()`
